spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: https://user-sead-group3.herokuapp.com
          predicates:
            - Path=/**
        - id: service
          uri: https://service-sead-group3.herokuapp.com
          predicates:
            - Path=/service/**
        - id: service_trans
          uri: https://service-trans-sead-group3.herokuapp.com
          predicates:
            - Path=/**